from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    query: str = Field(..., max_length=100, description="User's chat query.")

    class Config:
        json_schema_extra = {
            "example": {
                "query": "Tell me about the latest advancements in AI."
            }
        }

class ChatResponse(BaseModel):
    query: str
    response: str = Field(..., description="Response generated by the chatbot.")
